#!/bin/bash
# =============================================================================
# FILE        : send_reports.sh
# PROJECT     : NSCS Linux Audit & Monitoring System — 2025/2026
# DESCRIPTION : Sends the latest audit report via email using msmtp over TLS.
#               Reads email config from email.conf in the project root.
# AUTHOR      : [Your Name]
# SHELL       : bash (compatible with any Linux shell)
# USAGE       : bash send_reports.sh [--short | --full | --gui]
#
# DEPENDS ON  : msmtp (installed by install.sh)
#               email.conf (in project root — see format below)
#               A report generated by audit_software.sh or generate_reports.sh
#
# EMAIL.CONF FORMAT (already in your repo root):
#   RECIPIENT_EMAIL=admin@example.com
#   SENDER_EMAIL=your_bot@gmail.com
#   REPORT_TYPE=full
# =============================================================================

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 0 — MODE & COLOR SETUP
# ─────────────────────────────────────────────────────────────────────────────
MODE="${1:---full}"

if [[ "$MODE" == "--gui" ]] || [[ "${NO_COLOR:-}" == "1" ]]; then
    GUI_MODE=1; MODE="--full"
else
    GUI_MODE=0
fi

if [[ $GUI_MODE -eq 0 ]]; then
    RED='\e[1;31m'; GREEN='\e[1;32m'; YELLOW='\e[1;33m'
    CYAN='\e[1;36m'; BLUE='\e[1;34m'; RESET='\e[0m'
else
    RED=''; GREEN=''; YELLOW=''; CYAN=''; BLUE=''; RESET=''
fi

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 1 — CONFIGURATION
#
# We load settings from email.conf (already in the repo root).
# SCRIPT_DIR resolves to the modules/ folder; we go one level up to find it.
# ─────────────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"          # One level up from modules/
EMAIL_CONF="$PROJECT_ROOT/email.conf"            # email.conf in project root

REPORT_DIR="$HOME/nscs_os_project/reports"
LOG_DIR="$HOME/nscs_os_project"
LOG_FILE="$LOG_DIR/audit.log"

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
HOSTNAME_VAL=$(hostname)

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 2 — LOAD email.conf
#
# email.conf uses simple KEY=VALUE format, one per line.
# source (or .) reads and executes the file in the current shell,
# making all KEY=VALUE assignments available as variables.
#
# Example email.conf content:
#   RECIPIENT_EMAIL=admin@example.com
#   SENDER_EMAIL=audit_bot@gmail.com
#   REPORT_TYPE=full
#
# IMPORTANT: Do NOT commit real passwords to GitHub.
# Use Gmail App Passwords (not your real password).
# Set them in ~/.msmtprc (never in email.conf which is in the repo).
# ─────────────────────────────────────────────────────────────────────────────
load_email_config() {
    if [[ -f "$EMAIL_CONF" ]]; then
        # shellcheck source=/dev/null
        source "$EMAIL_CONF"
        echo -e "${GREEN}[ OK ] Email config loaded from $EMAIL_CONF${RESET}"
    else
        echo -e "${YELLOW}[WARN] email.conf not found at $EMAIL_CONF${RESET}"
        echo -e "${YELLOW}[WARN] Using default values — edit email.conf before sending.${RESET}"
    fi

    # Set defaults if not defined in email.conf
    RECIPIENT_EMAIL="${RECIPIENT_EMAIL:-admin@example.com}"
    SENDER_EMAIL="${SENDER_EMAIL:-audit_bot@gmail.com}"
    REPORT_TYPE="${REPORT_TYPE:-full}"

    echo -e "  Recipient : $RECIPIENT_EMAIL"
    echo -e "  Sender    : $SENDER_EMAIL"
    echo -e "  Report    : $REPORT_TYPE"
}

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 3 — HELPER FUNCTIONS
# ─────────────────────────────────────────────────────────────────────────────
info() { echo -e "${GREEN}[ OK ] $1${RESET}"; }
warn() { echo -e "${YELLOW}[WARN] $1${RESET}"; }
err()  { echo -e "${RED}[ERROR] $1${RESET}"; }

log() {
    mkdir -p "$LOG_DIR" 2>/dev/null
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] EMAIL: $1" >> "$LOG_FILE"
}

check_cmd() { command -v "$1" &>/dev/null; }

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 4 — FIND THE MOST RECENT REPORT FILE
#
# We search the reports directory for the most recently modified .txt report.
# 'find' lists all matching files, 'sort' orders them by name (timestamp
# in filename ensures newest = last alphabetically), 'tail -1' takes the last.
# ─────────────────────────────────────────────────────────────────────────────
find_report() {
    echo ""
    echo ">>> Searching for latest report..."

    # If audit_software.sh exported the path in the same session, use it
    if [[ -n "${LAST_SOFTWARE_REPORT:-}" ]] && [[ -f "$LAST_SOFTWARE_REPORT" ]]; then
        REPORT_FILE="$LAST_SOFTWARE_REPORT"
        info "Using report from current session: $REPORT_FILE"
        return 0
    fi

    # Otherwise find most recent report of the requested type
    REPORT_FILE=$(find "$REPORT_DIR" \
        -name "*${REPORT_TYPE}*.txt" \
        -type f \
        2>/dev/null \
        | sort | tail -1)

    # If still not found, take the absolute newest .txt report
    if [[ -z "$REPORT_FILE" ]] || [[ ! -f "$REPORT_FILE" ]]; then
        REPORT_FILE=$(find "$REPORT_DIR" \
            -name "*.txt" \
            -type f \
            2>/dev/null \
            | sort | tail -1)
    fi

    if [[ -z "$REPORT_FILE" ]] || [[ ! -f "$REPORT_FILE" ]]; then
        err "No report file found in $REPORT_DIR"
        err "Please run audit_software.sh first to generate a report."
        log "FAILED — No report file found."
        exit 1
    fi

    info "Report found: $REPORT_FILE"
}

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 5 — VERIFY MSMTP IS CONFIGURED
#
# WHAT IS msmtp?
#   A lightweight, standards-compliant SMTP client for Linux.
#   It reads SMTP credentials from ~/.msmtprc and sends email via any
#   SMTP server (Gmail, Outlook, custom server, etc.).
#   It uses STARTTLS (port 587) or TLS (port 465) for secure delivery.
#
# HOW TO SET UP ~/.msmtprc (run this ONCE manually):
#
# 1. Install msmtp (done by install.sh):
#      sudo apt install msmtp msmtp-mta -y
#
# 2. Create the config file:
#      nano ~/.msmtprc
#
# 3. Paste this content (replace YOUR values):
#    ─────────────────────────────────────────────────
#    defaults
#    auth           on
#    tls            on
#    tls_trust_file /etc/ssl/certs/ca-certificates.crt
#    logfile        ~/.msmtp.log
#
#    account        gmail
#    host           smtp.gmail.com
#    port           587
#    from           your_email@gmail.com
#    user           your_email@gmail.com
#    password       YOUR_APP_PASSWORD_HERE
#
#    account default : gmail
#    ─────────────────────────────────────────────────
#
# 4. Secure the file (REQUIRED — msmtp refuses to work otherwise):
#      chmod 600 ~/.msmtprc
#
# 5. For Gmail: create an App Password at:
#      https://myaccount.google.com/apppasswords
#    Select "Mail" + "Linux device" → copy the 16-character password.
#    Paste it as the 'password' value in ~/.msmtprc.
#    NEVER use your real Gmail password here.
# ─────────────────────────────────────────────────────────────────────────────
verify_msmtp() {
    echo ""
    echo ">>> Verifying msmtp configuration..."

    # Check msmtp is installed
    if ! check_cmd "msmtp"; then
        err "msmtp is not installed."
        warn "Run: sudo apt install msmtp msmtp-mta -y"
        log "FAILED — msmtp not installed."
        exit 1
    fi
    info "msmtp found: $(command -v msmtp)"

    # Check ~/.msmtprc exists
    MSMTP_RC="$HOME/.msmtprc"
    if [[ ! -f "$MSMTP_RC" ]]; then
        err "~/.msmtprc not found."
        warn "Create it following the instructions in send_reports.sh (Section 5)."
        warn "Then run: chmod 600 ~/.msmtprc"
        log "FAILED — ~/.msmtprc missing."
        exit 1
    fi

    # Check file permissions — must be 600 (read/write for owner only)
    # This is a security requirement: your password lives in this file.
    PERMS=$(stat -c "%a" "$MSMTP_RC" 2>/dev/null)
    if [[ "$PERMS" != "600" ]]; then
        warn "~/.msmtprc has permissions $PERMS — fixing to 600."
        chmod 600 "$MSMTP_RC"
        info "Permissions fixed to 600."
    fi

    info "msmtp configuration verified."
}

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 6 — BUILD THE EMAIL MESSAGE
#
# HOW EMAIL WORKS (MIME FORMAT):
#   Email is just structured plain text with special headers.
#   MIME (Multipurpose Internet Mail Extensions) allows attachments.
#
#   An email with attachment has:
#   1. Headers: From, To, Subject, Content-Type with boundary
#   2. Part 1: text body (what you read in the email)
#   3. Part 2: attachment (file encoded in base64)
#
#   base64 = a way to represent binary/text data using only printable
#   characters (A-Z, a-z, 0-9, +, /) so it can travel through email safely.
#
#   The "boundary" string is a unique separator between parts.
#   msmtp reads the email from stdin and delivers it via SMTP.
# ─────────────────────────────────────────────────────────────────────────────
build_and_send_email() {
    echo ""
    echo ">>> Building email message..."

    REPORT_SIZE=$(du -sh "$REPORT_FILE" 2>/dev/null | cut -f1)
    REPORT_HASH=$(cat "${REPORT_FILE}.sha256" 2>/dev/null || echo "N/A")
    ATTACHMENT_NAME=$(basename "$REPORT_FILE")

    # Unique boundary string — separates email body from attachment
    BOUNDARY="NSCS_AUDIT_$(date +%s)_BOUNDARY"

    # Email subject line
    SUBJECT="[SYS-AUDIT] $HOSTNAME_VAL — $(echo $REPORT_TYPE | tr a-z A-Z) Report — $TIMESTAMP"

    # Plain text body of the email
    EMAIL_BODY="Linux System Audit Report — $(echo $REPORT_TYPE | tr a-z A-Z)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Host        : $HOSTNAME_VAL
  Date & Time : $TIMESTAMP
  Report Type : $(echo $REPORT_TYPE | tr a-z A-Z) AUDIT
  File Size   : $REPORT_SIZE
  SHA256 Hash : $REPORT_HASH
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The complete audit report is attached to this email.
Please review it for security anomalies and take action
on any [!!] WARNING or [RISK] items found.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This message was generated automatically by:
NSCS Linux Audit & Monitoring System v2.0.26
NSCS Cybersecurity Project — 2025/2026
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Do not reply to this automated message]"

    # Encode the report file as base64 for attachment
    # base64 converts each 3 bytes → 4 printable characters
    echo ">>> Encoding report as base64 attachment..."
    ATTACHMENT_B64=$(base64 "$REPORT_FILE" 2>/dev/null)
    if [[ -z "$ATTACHMENT_B64" ]]; then
        err "Failed to encode report file."
        log "FAILED — base64 encoding failed for $REPORT_FILE"
        exit 1
    fi
    info "Report encoded — size: $REPORT_SIZE"

    # Write the complete MIME email to a temp file
    EMAIL_TMP=$(mktemp /tmp/nscs_email_XXXXXX.eml)

    cat > "$EMAIL_TMP" <<EOF
From: NSCS Audit Bot <$SENDER_EMAIL>
To: $RECIPIENT_EMAIL
Subject: $SUBJECT
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="$BOUNDARY"
X-Mailer: NSCS-Audit-System/2.0

--$BOUNDARY
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

$EMAIL_BODY

--$BOUNDARY
Content-Type: text/plain; name="$ATTACHMENT_NAME"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="$ATTACHMENT_NAME"

$ATTACHMENT_B64

--${BOUNDARY}--
EOF

    info "Email message built."
    echo "  From    : $SENDER_EMAIL"
    echo "  To      : $RECIPIENT_EMAIL"
    echo "  Subject : $SUBJECT"
    echo "  Attach  : $ATTACHMENT_NAME ($REPORT_SIZE)"

    # ── SEND THE EMAIL ────────────────────────────────────────────────────
    echo ""
    echo ">>> Sending email via msmtp (SMTP/TLS)..."

    # msmtp reads the email from stdin (<) and sends to the recipient
    # -a default = use the "default" account defined in ~/.msmtprc
    if msmtp -a default "$RECIPIENT_EMAIL" < "$EMAIL_TMP" 2>/dev/null; then
        info "Email sent successfully to $RECIPIENT_EMAIL"
        log "SUCCESS — Report emailed to $RECIPIENT_EMAIL | File: $REPORT_FILE"
        rm -f "$EMAIL_TMP"
        return 0
    else
        err "Email sending failed!"
        warn "Check ~/.msmtp.log for detailed error information."
        warn "Common causes:"
        warn "  1. Wrong App Password in ~/.msmtprc"
        warn "  2. Gmail 2FA not enabled (required for App Passwords)"
        warn "  3. Network/firewall blocking port 587"
        log "FAILED — msmtp returned error for recipient: $RECIPIENT_EMAIL"
        rm -f "$EMAIL_TMP"
        return 1
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 7 — MAIN EXECUTION
# ─────────────────────────────────────────────────────────────────────────────
main() {
    echo ""
    echo "=================================================="
    echo "  >>> SEND REPORTS MODULE — Initializing..."
    echo "  Hostname : $HOSTNAME_VAL"
    echo "  Time     : $TIMESTAMP"
    echo "=================================================="

    mkdir -p "$LOG_DIR" 2>/dev/null

    load_email_config      # Load email.conf settings
    verify_msmtp           # Check msmtp is installed and configured
    find_report            # Locate the report file to send
    build_and_send_email   # Build MIME email and deliver it

    echo ""
    echo "[ OK ] Email module complete!"
    echo ""
}

# Entry point
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
