#!/bin/bash
################################################################################
# NSCS Cron Runner — Auto-generated by setup_cron.sh
# Called by cron daemon every day at 04:00 AM
#
# DO NOT EDIT MANUALLY — regenerate with setup_cron.sh
################################################################################

# ── Environment setup ─────────────────────────────────────────────────────────
# CRITICAL: cron runs with a minimal environment — none of your .bashrc
# variables exist. We must define everything from scratch.

export HOME="${HOME:-/home/$(whoami)}"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export TERM="dumb"      # no color codes — cron has no terminal
export NO_COLOR="1"

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE_DIR="$HOME/nscs_os_project"
MODULES_DIR="$BASE_DIR/modules"
LOG_FILE="$BASE_DIR/cron.log"
STATUS_JSON="$BASE_DIR/cron_status.json"
REPORT_DIR="$BASE_DIR/reports"
ALERT_EMAIL_CONF="$BASE_DIR/email.conf"

mkdir -p "$BASE_DIR" "$REPORT_DIR"

# ── Logging functions ─────────────────────────────────────────────────────────
# Every line written to cron.log has:
#   [TIMESTAMP] [LEVEL] MESSAGE
# This makes it easy to grep for errors: grep '\[ERROR\]' cron.log

log_info()  { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO ]  $*" | tee -a "$LOG_FILE"; }
log_ok()    { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [ OK  ]  $*" | tee -a "$LOG_FILE"; }
log_warn()  { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [WARN ]  $*" | tee -a "$LOG_FILE"; }
log_error() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [ERROR]  $*" | tee -a "$LOG_FILE"; }

# ── Session tracking ──────────────────────────────────────────────────────────
RUN_ID="run_$(date +%Y%m%d_%H%M%S)"
SESSION_START=$(date +%s)
FAILED_MODULES=()
SUCCESS_MODULES=()

# ── Start of session ──────────────────────────────────────────────────────────
{
echo "════════════════════════════════════════════════════════"
echo "  NSCS CRON RUNNER — SESSION START"
echo "  Run ID  : $RUN_ID"
echo "  Started : $(date)"
echo "  Host    : $(hostname)"
echo "  User    : $(whoami)"
echo "════════════════════════════════════════════════════════"
} | tee -a "$LOG_FILE"

log_info "Session $RUN_ID started"

# ── Module runner function ────────────────────────────────────────────────────
# run_module SCRIPT_NAME LABEL
#
# HOW FAILURE HANDLING WORKS:
#   Every Linux command returns an "exit code" when it finishes:
#     0  = success (by convention)
#     1+ = failure (the number indicates the type of error)
#
#   $? contains the exit code of the last command.
#   We check it after every module and log accordingly.
#
#   timeout 300 bash ...  = kill the process after 5 minutes
#   This prevents a stuck module from blocking the entire cron job.

run_module() {
    local script="$1"
    local label="$2"
    local script_path="$MODULES_DIR/$script"

    log_info "Starting: $label ($script)"

    # Check script exists
    if [ ! -f "$script_path" ]; then
        log_warn "SKIPPED: $script — file not found at $script_path"
        return 0   # Not a failure — just skip missing modules
    fi

    # Make executable
    chmod +x "$script_path"

    # Run with:
    #   timeout 300  = max 5 minutes before force-kill
    #   --gui        = skip interactive prompts
    #   >> $LOG_FILE = append all output to log
    #   2>&1         = also capture stderr (error output) to log
    local start_time; start_time=$(date +%s)

    timeout 300 bash "$script_path" --gui >> "$LOG_FILE" 2>&1
    local exit_code=$?
    local end_time; end_time=$(date +%s)
    local duration=$(( end_time - start_time ))

    # Interpret exit code
    if [ $exit_code -eq 0 ]; then
        # SUCCESS
        log_ok "$label completed in ${duration}s (exit 0)"
        SUCCESS_MODULES+=("$label")

    elif [ $exit_code -eq 124 ]; then
        # TIMEOUT (exit code 124 = timeout killed the process)
        log_error "$label TIMED OUT after 300s — killed"
        FAILED_MODULES+=("$label:TIMEOUT after 300s")

    else
        # FAILURE (non-zero exit code)
        log_error "$label FAILED with exit code $exit_code (duration: ${duration}s)"
        FAILED_MODULES+=("$label:exit code $exit_code")
    fi

    return $exit_code
}

# ── Run all modules in order ──────────────────────────────────────────────────
# Order matters: hardware/software audits must run BEFORE report generation
# because generate_reports.sh reads the JSON files they produce.

log_info "--- Phase 1: Audit ---"
run_module "audit_hardware_v2.sh" "Hardware Audit"
run_module "audit_software.sh"    "Software Audit"

log_info "--- Phase 2: Reports ---"
run_module "generate_reports.sh"  "Report Generation"

log_info "--- Phase 3: Email ---"
run_module "send_reports.sh"      "Email Transmission"

log_info "--- Phase 5: Remote ---"
run_module "remote_monitor.sh"    "Remote Monitoring"

# ── Session summary ───────────────────────────────────────────────────────────
SESSION_END=$(date +%s)
TOTAL_DURATION=$(( SESSION_END - SESSION_START ))
FAIL_COUNT=${#FAILED_MODULES[@]}
OK_COUNT=${#SUCCESS_MODULES[@]}

{
echo "════════════════════════════════════════════════════════"
echo "  NSCS CRON RUNNER — SESSION COMPLETE"
echo "  Run ID    : $RUN_ID"
echo "  Finished  : $(date)"
echo "  Duration  : ${TOTAL_DURATION}s"
echo "  Succeeded : $OK_COUNT module(s)"
echo "  Failed    : $FAIL_COUNT module(s)"
if (( FAIL_COUNT > 0 )); then
    echo "  Failures  :"
    for f in "${FAILED_MODULES[@]}"; do
        echo "    - $f"
    done
fi
echo "════════════════════════════════════════════════════════"
} | tee -a "$LOG_FILE"

# ── Write machine-readable status JSON ───────────────────────────────────────
# This lets other tools (or the GUI) read cron status programmatically

FAIL_JSON=""
for f in "${FAILED_MODULES[@]}"; do
    mod="${f%%:*}"; reason="${f##*:}"
    FAIL_JSON+="    {\"module\":\"$mod\",\"reason\":\"$reason\"},"
done
FAIL_JSON="${FAIL_JSON%,}"

OK_JSON=""
for s in "${SUCCESS_MODULES[@]}"; do
    OK_JSON+="\"$s\","
done
OK_JSON="${OK_JSON%,}"

OVERALL="SUCCESS"
(( FAIL_COUNT > 0 )) && OVERALL="PARTIAL_FAILURE"
(( OK_COUNT == 0 && FAIL_COUNT > 0 )) && OVERALL="TOTAL_FAILURE"

cat <<EOF > "$STATUS_JSON"
{
  "run_id": "$RUN_ID",
  "timestamp": "$(date)",
  "host": "$(hostname)",
  "user": "$(whoami)",
  "overall_status": "$OVERALL",
  "duration_seconds": $TOTAL_DURATION,
  "succeeded": $OK_COUNT,
  "failed": $FAIL_COUNT,
  "successful_modules": [$OK_JSON],
  "failed_modules": [
$FAIL_JSON
  ]
}
EOF

# ── FAILURE HANDLING — Send alert email if anything failed ────────────────────
#
# CONCEPT: Failure notification
#
#   A cron job that silently fails is DANGEROUS — you think your system
#   is being audited but it isn't. We solve this by sending an alert email
#   when any module fails.
#
#   We reuse the email credentials from send_reports.sh (email.conf)
#   so no extra configuration is needed.
#
#   The alert email contains:
#     - Which modules failed
#     - The error reason
#     - The full log file path to investigate
#
# ─────────────────────────────────────────────────────────────────────────────

if (( FAIL_COUNT > 0 )); then
    log_warn "Failures detected — attempting alert email..."

    if [ -f "$ALERT_EMAIL_CONF" ]; then
        source "$ALERT_EMAIL_CONF" 2>/dev/null

        if [ -n "$SMTP_FROM" ] && [ -n "$SMTP_PASS" ] && [ -n "$SMTP_TO" ]; then
            FAIL_LIST=""
            for f in "${FAILED_MODULES[@]}"; do
                FAIL_LIST+="  - $f\n"
            done

            python3 - <<PYEOF 2>/dev/null
import smtplib, ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

msg = MIMEMultipart()
msg["From"]    = "NSCS Cron <$SMTP_FROM>"
msg["To"]      = "$SMTP_TO"
msg["Subject"] = "[NSCS ALERT] Cron job failures on $(hostname) — $RUN_ID"

body = """NSCS Automated Audit System — FAILURE ALERT

Host     : $(hostname)
Run ID   : $RUN_ID
Time     : $(date)
Status   : $OVERALL

Failed modules ($FAIL_COUNT):
$(printf '%b' "$FAIL_LIST")
Successful modules ($OK_COUNT):
$(printf '%s\n' "${SUCCESS_MODULES[@]}" | sed 's/^/  - /')

Full log : $LOG_FILE
Status   : $STATUS_JSON

This is an automated alert from your NSCS cron runner.
"""
msg.attach(MIMEText(body, "plain"))

try:
    ctx = ssl.create_default_context()
    with smtplib.SMTP("smtp.gmail.com", 587, timeout=15) as s:
        s.ehlo(); s.starttls(context=ctx); s.ehlo()
        s.login("$SMTP_FROM", "$SMTP_PASS")
        s.sendmail("$SMTP_FROM", "$SMTP_TO", msg.as_string())
    print("[$(date '+%Y-%m-%d %H:%M:%S')] [ OK  ]  Alert email sent to $SMTP_TO")
except Exception as e:
    print(f"[$(date '+%Y-%m-%d %H:%M:%S')] [WARN ]  Alert email failed: {e}")
PYEOF
            log_ok "Alert email sent to $SMTP_TO"
        else
            log_warn "Alert email skipped — incomplete credentials in email.conf"
        fi
    else
        log_warn "Alert email skipped — no email.conf found"
        log_info "Run send_reports.sh once in terminal to configure email"
    fi
fi

# Exit with number of failures as exit code
# 0 = total success, 1+ = number of failed modules
exit $FAIL_COUNT
